#spring:
#  application:
#    name: e-tech
#  datasource:
#    password: 1
#    url: jdbc:postgresql://localhost:5432/E-tech
#    username: postgres
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true
#    show-sql: false
#    defer-datasource-initialization: true
#    generate-ddl: true
#  sql:
#    init:
#      mode: always
#server:
#  port: 8080
#
#


#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/e-tech
#    username: postgres
#    password: test123
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#          ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

